id: IC19A8BA7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:00:28+00:00'
last_modified: '2022-06-09T04:54:32.797648+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5099
  title: མཆོད་ཡོན་ཉི་ཟླ་ཟུང་གི་ཁྲིམས་ཡིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3BFD:
      image_group_id: I1KG5111
      title: Volume 1 of mchod yon nyi zla zung gi khrims yig
      total_pages: 114
      order: 1
      base_file: 3BFD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
