id: P007102
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5099
  title: མཆོད་ཡོན་ཉི་ཟླ་ཟུང་གི་ཁྲིམས་ཡིག
  author: ''
  volumes:
    c8059e7a7624402d9887be43e5dfc410:
      image_group_id: I1KG5111
      title: Volume 1 of mchod yon nyi zla zung gi khrims yig
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
ebook_metadata:
  title: མཆོད་ཡོན་ཉི་ཟླ་ཟུང་གི་ཁྲིམས་ཡིག
  author: ''
  sku: P007102
  cover: cover.jpg
  layers:
  - pagination
