id: P007102
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5099
  title: མཆོད་ཡོན་ཉི་ཟླ་ཟུང་གི་ཁྲིམས་ཡིག
  author: ''
  volumes:
    1e0bb73b109845e09336dca3ba830bdb:
      image_group_id: I1KG5111
      title: ''
      volume_number: 1
      total_pages: 114
ebook_metadata:
  title: མཆོད་ཡོན་ཉི་ཟླ་ཟུང་གི་ཁྲིམས་ཡིག
  author: ''
  sku: P007102
  cover: cover.jpg
  layers:
  - pagination
