id: P007102
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG5099
  title: མཆོད་ཡོན་ཉི་ཟླ་ཟུང་གི་ཁྲིམས་ཡིག
  author: ''
  volumes:
    c8059e7a7624402d9887be43e5dfc410:
      image_group_id: I1KG5111
      title: Volume 1 of mchod yon nyi zla zung gi khrims yig
      volume_number: 1
      total_pages: 114
      base_file: v001.txt
